# Generated by Django 4.2.13 on 2024-06-30 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='column',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.column', verbose_name='Column'),
        ),
        migrations.AddField(
            model_name='task',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='column_tasks', to='projects.column', verbose_name='Column'),
        ),
    ]
